# Generated by Django 6.0.2 on 2026-02-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_cats_slug_alter_post_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cats',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cat',
            new_name='category',
        ),
    ]
